"""add count column to association table

Revision ID: c24828ff6b04
Revises: eedb808e21ce
Create Date: 2025-05-28 17:37:04.203530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c24828ff6b04'
down_revision: Union[str, None] = 'eedb808e21ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_product_association', sa.Column('count', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_product_association', 'count')
    # ### end Alembic commands ###
